name: Mirror to Secondary Repo

on:
  push:
    branches:
      - master   # adjust if you want multiple branches mirrored

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push to mirror
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/ncssmtsa2025git/ncssm-tsa-hub-deploy.git
          git push --force --mirror mirror
